# Permalinks
permalink:        /posts/:title.html

# Setup
url:              https://mayanbin.com
img_url:          https://cdn.jsdelivr.net/gh/infp/infp.github.io/images

# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            Mallji的博客
tagline:          Mallji的博客

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  只关于[代码]。

notification:     |

plugins:
  - jekyll-seo-tag



# Google Analytics tracking ID
# TODO: 如果使用本主题，请务必替换此处的 Google 统计代码，否则你的站点将无法获得统计数据
analytics:        'UA-32028925-2'

# Fallback image and color if not overwritten for tag or post
image:            /public/images/flower.jpg
color:            '#dc322f'

author:
  name:           Mallji
  email:          2585874313@qq.com
  avatar:         /public/images/avator.jpg
  github:         Mallji
  linkedin:       Mallji
  facebook:       Mallji
  steam:          Mallji

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是Mallji,如果你觉得本文不错，可略表心意，[请我喝一杯咖啡](https://myanbin.github.io/about.html#buymeacoffee)。


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
